# Generated by Django 6.0.7 on 2026-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_querys', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryrelatorio',
            name='grupos_permitidos',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
